@startuml Get Hotel by id

title "Get Hotel by ID (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<controllers>>\n:hotels" as controllersHotel
participant "<<model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelDatabase

client->server ++:req.get('/hotels/:id')
server->routerHotels ++:app.use('/hotels/:id',hotel)
routerHotels -> controllersHotel ++:getHotel()
controllersHotel->modelHotel ++:findById(req.params.id)
modelHotel ->HotelDatabase ++: HotelSchema
HotelDatabase --> modelHotel --: hotel
controllersHotel <-- modelHotel --: hotel
controllersHotel->client --:response

@enduml
