@startuml Hotel Registration System Use Case Diagram
left to right direction

actor "User" as user
rectangle "\t\t\t\tHotel Registration System\t\t\t\t" as HotelRegistrationSystem {    
    usecase "Register" as register
    usecase "Login" as login
    usecase "Logout" as logout
    usecase "View\nHotels" as viewHotels
    usecase "Create\nHotels" as createHotel
    usecase "Delete\nHotels" as deleteHotel
    usecase "View\nBookings" as viewBookings
    usecase "Create\nBooking" as createBooking
    usecase "Edit\nBooking" as editBooking
    usecase "Delete\nBooking" as deleteBooking
    usecase "Get\nBooking PDF" as getBookingPDF
}

actor "Admin" as admin


user -- register
user -- login
user -- logout

user -- viewHotels

user -- viewBookings
user -- createBooking
user -- editBooking
user -- deleteBooking
user -- getBookingPDF
' =====================

register -- admin
login -- admin
logout -- admin

viewHotels -- admin
createHotel -- admin
deleteHotel -- admin

viewBookings -- admin
createBooking -- admin
editBooking -- admin
deleteBooking -- admin
getBookingPDF -- admin
' =====================
@enduml