@startuml Login (POST)

' header Hotel Registration Sequence Diagram
title "Login (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuths
participant "<<model>>\n:User" as modelAuth
database "<<MongoDB>>\n:users" as UsersDatabase
participant "<<object>>\n:User" as userObject

client -> server ++:req.post('/auth/login')
server -> routerAuth ++:app.use('/auth',auth)
routerAuth -> controllersAuths ++:login()
activate controllersAuths

controllersAuths -> modelAuth ++:create(req.body)
modelAuth -> UsersDatabase ++: AuthSchema
UsersDatabase --> userObject: 

UsersDatabase --> modelAuth --: user
controllersAuths <-- modelAuth --:user

controllersAuths -> userObject ++: matchPassword(req.body.password)

controllersAuths -> controllersAuths ++: sendTokenResponse(user)
controllersAuths -> userObject :getSignedJwtToken()
userObject --> controllersAuths --: token

controllersAuths -> client --:response
deactivate controllersAuths

@enduml
