@startuml Logout (GET)

' header Hotel Registration Sequence Diagram
title "Logout (GET)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuths

client -> server ++:req.get('/auth/logout')
server -> routerAuth ++:app.use('/auth',auth)
routerAuth -> controllersAuths ++:logout()
controllersAuths -> client --:response

@enduml
